# Site settings
title: Goo Learn
email: create@goocreate.com
description: Goo Technologies Learn
baseurl: "/learn"
url: "http://gootechnologies.github.io/learn"
twitter_username: GooTechnologies
github_username:  GooTechnologies

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass

highlighter: pygments

defaults:
  -
    scope:
      path: "manual"
    values:
      layout: "page"
