# Site settings
title: Goo Learn
email: create@goocreate.com
description: Goat technologies
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gootechnologies.github.io/learn/" # the base hostname & protocol for your site
twitter_username: GooTechnologies
github_username:  GooTechnologies

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass