# Site settings
title: Goo Create Learn
email: create@goocreate.com
description: Goo Learn | Resources for Learning Goo Create and Goo Engine
copyright_notice: © Copyright 2015 Goo Technologies.
baseurl: ""
url: "http://gootechnologies.github.io/learn"
twitter_username: GooTechnologies
github_username:  GooTechnologies

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass

highlighter: pygments

defaults:
  -
    scope:
      path: "manual"
    values:
      layout: "manual"
  -
    scope:
      path: "tutorials"
    values:
      layout: "tutorial"

# The menus take a long time to render. Comment out the following line to skip rendering them.
render_navigation: true
render_menus: true
render_breadcrumbs: true
render_prev_next_btns: true