# Site settings
title: Goo Create Learn
email: create@goocreate.com
description: Goo Learn | Resources for Learning Goo Create and Goo Engine
copyright_notice: © Copyright 2015 Goo Technologies.
baseurl: "/learn"
url: "http://gootechnologies.github.io/learn"
twitter_username: GooTechnologies
github_username:  GooTechnologies

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass

highlighter: pygments

defaults:
  -
    scope:
      path: "manual"
    values:
      layout: "page"
